"""API models (response bodies) for the analysis endpoints.

Built from the persisted analysis state (AnalysisStore). Internal details (build and
index IDs, hashes, the vector dimension, Neo4j queries) are not exposed.
"""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.services.analysis_store import AnalysisJob, AnalysisResult, AnalysisState


class GraphSummary(BaseModel):
    files: int = Field(description="Files analyzed")
    entities: int = Field(description="Nodes of the project's knowledge graph")
    relationships: int = Field(description="Relationships (CONTAINS, CALLS, IMPORTS...)")
    entities_by_type: dict[str, int]
    relationships_by_type: dict[str, int]
    unresolved_references: int = Field(
        description="Calls or imports whose target is not in the project (e.g. libraries)"
    )
    stale_entities_removed: int = Field(description="Removed by this analysis (code deleted)")


class VectorSummary(BaseModel):
    files: int = Field(description="Files chunked")
    chunks: int = Field(description="Code chunks indexed for semantic search")
    chunks_by_type: dict[str, int]
    embedding_model: str
    stale_chunks_removed: int = Field(description="Removed by this analysis (code deleted)")


class AnalysisChangesResponse(BaseModel):
    """What this analysis really processed. A full analysis processes everything."""

    files_added: int
    files_modified: int
    files_unchanged: int
    files_deleted: int
    files_parsed: int = Field(description="Files parsed by this analysis")
    nodes_written: int
    nodes_deleted: int
    relationships_written: int
    relationships_deleted: int
    chunks_embedded: int = Field(description="Embeddings generated by this analysis")
    chunks_reused: int = Field(description="Chunks whose existing vector was kept")
    chunks_updated: int = Field(description="Kept vectors whose metadata (lines) was refreshed")
    chunks_deleted: int


class AnalysisResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "project_id": "3f2b9c0e1a4d4e5f8a7b6c5d4e3f2a1b",
                    "status": "ready",
                    "mode": "incremental",
                    "graph": {
                        "files": 4, "entities": 18, "relationships": 28,
                        "entities_by_type": {"Class": 4, "File": 4, "Function": 3, "Method": 7},
                        "relationships_by_type": {"CALLS": 9, "CONTAINS": 14, "DEPENDS_ON": 2,
                                                  "IMPORTS": 2, "INHERITS": 1},
                        "unresolved_references": 8, "stale_entities_removed": 0,
                    },
                    "vectors": {
                        "files": 4, "chunks": 16,
                        "chunks_by_type": {"class": 4, "file": 2, "function": 3, "method": 7},
                        "embedding_model": "BAAI/bge-m3", "stale_chunks_removed": 0,
                    },
                    "changes": {
                        "files_added": 0, "files_modified": 1, "files_unchanged": 3,
                        "files_deleted": 0, "files_parsed": 1, "nodes_written": 1,
                        "nodes_deleted": 0, "relationships_written": 2,
                        "relationships_deleted": 0, "chunks_embedded": 1, "chunks_reused": 15,
                        "chunks_updated": 0, "chunks_deleted": 0,
                    },
                    "failed_files": 0,
                    "warnings": [],
                    "duration_seconds": 1.4,
                    "analyzed_at": "2026-10-03T18:30:00Z",
                }
            ]
        }
    )  # fmt: skip

    project_id: str
    status: Literal["ready"] = Field(description="This report describes a finished analysis")
    mode: Literal["full", "incremental"] = Field(
        description="full: everything was processed; incremental: only what changed"
    )
    graph: GraphSummary
    vectors: VectorSummary
    changes: AnalysisChangesResponse
    failed_files: int = Field(description="Files that could not be read or parsed (skipped)")
    warnings: list[str]
    duration_seconds: float
    analyzed_at: datetime = Field(description="When this analysis finished (UTC)")

    @classmethod
    def from_result(cls, result: AnalysisResult) -> "AnalysisResponse":
        warnings = []
        if result.failed_files:
            warnings.append(f"{result.failed_files} file(s) could not be parsed and were skipped.")
        if result.chunks == 0:
            warnings.append("No code could be indexed: chat will not find anything to answer from.")
        changes = result.changes
        return cls(
            project_id=result.project_id,
            status="ready",
            mode=result.mode,  # type: ignore[arg-type]
            graph=GraphSummary(
                files=result.files,
                entities=result.entities,
                relationships=result.relationships,
                entities_by_type=result.entities_by_type,
                relationships_by_type=result.relationships_by_type,
                unresolved_references=result.unresolved_references,
                stale_entities_removed=changes.nodes_deleted,
            ),
            vectors=VectorSummary(
                files=result.files,
                chunks=result.chunks,
                chunks_by_type=result.chunks_by_type,
                embedding_model=result.embedding_model,
                stale_chunks_removed=changes.chunks_deleted,
            ),
            changes=AnalysisChangesResponse(**vars(changes)),
            failed_files=result.failed_files,
            warnings=warnings,
            duration_seconds=result.duration_seconds,
            analyzed_at=result.analyzed_at,
        )


class AnalysisJobResponse(BaseModel):
    """The latest analysis job of a project."""

    job_id: str
    status: Literal["queued", "running", "ready", "failed"]
    mode: Literal["full", "incremental"] | None = Field(
        description="Known once the changes are detected"
    )
    phase: str | None = Field(
        description="preparing, detecting_changes, parsing, resolving, embedding, graph, "
        "vector_index or finalizing"
    )
    completed: int | None = Field(description="Real count of the current phase, when countable")
    total: int | None
    unit: Literal["files", "chunks"] | None
    queued_at: datetime
    started_at: datetime | None
    finished_at: datetime | None
    error: str | None = Field(description="Why the job failed (safe to display)")

    @classmethod
    def from_job(cls, job: AnalysisJob) -> "AnalysisJobResponse":
        return cls(**{**vars(job), "status": job.status.value})


class AnalysisStatusResponse(BaseModel):
    """Whether a project is ready for chat, its current or last job, and its last report."""

    project_id: str
    status: Literal["not_analyzed", "queued", "running", "ready", "failed"] = Field(
        description="queued/running: a job is in progress; failed: the last job failed "
        "(`analysis` is still set when the previous analysis remains valid)"
    )
    job: AnalysisJobResponse | None
    analysis: AnalysisResponse | None = Field(
        description="The report of the analysis whose data is in the databases; null when "
        "there is none (never analyzed, or a failure while writing)"
    )

    @classmethod
    def from_state(cls, state: AnalysisState) -> "AnalysisStatusResponse":
        return cls(
            project_id=state.project_id,
            status=state.status,  # type: ignore[arg-type]
            job=None if state.job is None else AnalysisJobResponse.from_job(state.job),
            analysis=None if state.result is None else AnalysisResponse.from_result(state.result),
        )
